theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
true-color = true
line-number = "relative"
insert-final-newline = false
   
[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding", "file-line-ending"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "â”‚"
render = true

[editor.file-picker]
git-ignore = false

[editor.lsp]
auto-signature-help = false
display-messages = true

# allow shift+x to reduce the size of an x selection

[keys.normal]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
